export const productos = [
  {
    id: 200,
    nombre: 'Peto Lakers Gold',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTnwUuaCac591FcxnwZ12iY11vZtrI4UvWsw&s',
    precio: 55,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Amarillo', 'Púrpura', 'Blanco'],
    descripcion: 'Inspirado en los Los Angeles Lakers, con tecnología de secado rápido y ajuste ergonómico.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 201,
    nombre: 'Peto Celtics Pride',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtujIQdkHWPrwRb3t0M6XI4psqKHTGuxyjkw&s',
    precio: 53,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Verde', 'Blanco', 'Negro'],
    descripcion: 'Peto ligero y duradero diseñado para la intensidad de los Boston Celtics.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 202,
    nombre: 'Peto Bulls Legacy',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGyH4yWffUTccyKZMWAb72ve2fwC-7J-ZrAw&s',
    precio: 58,
    tallas: ['M', 'L', 'XL'],
    colores: ['Rojo', 'Negro', 'Blanco'],
    descripcion: 'Estilo clásico de los Chicago Bulls con materiales transpirables y de alto rendimiento.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 203,
    nombre: 'Peto Warriors Dynasty',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEds6HPCb08sXBFv-b9_2YZgYjOpwxSRjBWQ&s',
    precio: 60,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Azul', 'Amarillo', 'Blanco'],
    descripcion: 'Diseñado para la velocidad y resistencia de los Golden State Warriors.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 204,
    nombre: 'Peto Nets Elite',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5QBUZVE_tggX4uuR301zEGKo8Nnu9Ty4GBg&s',
    precio: 52,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Gris'],
    descripcion: 'Peto técnico con soporte muscular inspirado en los Brooklyn Nets.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 205,
    nombre: 'Peto Heat Fire',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH-W3rmC6HW34ltlBEar-llTD8F82Rg3OS1g&s',
    precio: 57,
    tallas: ['M', 'L', 'XL'],
    colores: ['Rojo', 'Negro', 'Blanco'],
    descripcion: 'Estilo enérgico de los Miami Heat con ajuste de compresión y tecnología antideslizante.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 206,
    nombre: 'Peto Suns Rising',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj7HA9HX9Piff9BHPgbDugc_AGKspexrWozQ&s',
    precio: 50,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Naranja', 'Púrpura', 'Blanco'],
    descripcion: 'Inspirado en los Phoenix Suns, con ventilación avanzada y diseño atlético.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 207,
    nombre: 'Peto Mavericks Court',
    imagen: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTWWfO-dwWQo9TH51M9koq4ek9XpDgN3kQfk65O-xtGmTRk37k-Dys03et6YzSOi6wz_qMPP_KNSHl9qLHWjkWedHcHDYU-BB4fy3Ux1WFebgCPM6yxrK7m&usqp=CAE',
    precio: 56,
    tallas: ['M', 'L', 'XL'],
    colores: ['Azul', 'Blanco', 'Negro'],
    descripcion: 'Peto técnico con máxima transpirabilidad para los Dallas Mavericks.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 208,
    nombre: 'Peto Knicks Hustle',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiiLWR9xSuEaJ2iGeF0r-bXXRgOXXZKnwONQ&s',
    precio: 51,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Naranja', 'Azul', 'Blanco'],
    descripcion: 'Diseño clásico de los New York Knicks con materiales ligeros y resistentes.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 209,
    nombre: 'Peto Jazz Rhythm',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPY29E7Pm_f9NxGl7vzliAeKITu-6G-BcjAg&s',
    precio: 55,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Púrpura', 'Verde', 'Blanco'],
    descripcion: 'Inspirado en la energía de los Utah Jazz, con tecnología anti-humedad.',
    categoria: 'petos',
    section: 'basquet',
  },
  {
    id: 300,
    nombre: 'Pantaloneta Nike Elite',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSryk89AVVfXo7PAOJf_pJwYIh5e9XQi4wYFQ&s',
    precio: 40,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Azul'],
    descripcion: 'Pantaloneta diseñada para jugadores de baloncesto con tecnología Dri-FIT.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 301,
    nombre: 'Pantaloneta Adidas Hoops',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7lB2BuTN96r5BhNuSENHBLLEBnGSBhtJ5bQ&s',
    precio: 38,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Rojo', 'Negro', 'Gris'],
    descripcion: 'Tejido transpirable ideal para entrenamientos y partidos casuales.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 302,
    nombre: 'Pantaloneta Spalding Court',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ8jhViCH2715w2Ua-W78fwuH_hZMBLlXYIA&s',
    precio: 35,
    tallas: ['M', 'L', 'XL'],
    colores: ['Blanco', 'Negro', 'Verde'],
    descripcion: 'Durabilidad y confort, perfecta para juegos intensos.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 303,
    nombre: 'Pantaloneta Jordan Jumpman',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVYiSQpbJrY_oG14n05CxTOvjZKSJ8gWQNDw&s',
    precio: 50,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Rojo'],
    descripcion: 'Estilo clásico con tecnología de ventilación avanzada.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 304,
    nombre: 'Pantaloneta Under Armour Dunk',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYSghJYA_Z6dM-vxHJAqrae3uIQx740JSqVw&s',
    precio: 42,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Azul', 'Negro', 'Naranja'],
    descripcion: 'Material ligero que permite máxima movilidad en la cancha.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 305,
    nombre: 'Pantaloneta Puma Fast Break',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy097r5KXzmWXsZlv81yuqN4GAT3NQo7_vFg&s',
    precio: 37,
    tallas: ['S', 'M', 'L'],
    colores: ['Amarillo', 'Gris', 'Blanco'],
    descripcion: 'Diseño moderno con ajuste cómodo para movimientos rápidos.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 306,
    nombre: 'Pantaloneta Reebok Slam',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTezp8d8WgD6RyuIuLQt5oBgL2tupbgoUzQAA&s',
    precio: 39,
    tallas: ['M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Verde'],
    descripcion: 'Ideal para entrenamientos y partidos de alto rendimiento.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 307,
    nombre: 'Pantaloneta Wilson Dunk Pro',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTATXFqKx5MaIDuAWZ0S4sKYheK0vXF3VNS9g&s',
    precio: 36,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Naranja', 'Blanco', 'Azul'],
    descripcion: 'Confección resistente para jugadores intensos.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 308,
    nombre: 'Pantaloneta Champion Crossover',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6o7x7p5HzkdBVrl8TbsvoDg6O1sngKTL1fQ&s',
    precio: 41,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Rojo', 'Negro', 'Gris'],
    descripcion: 'Comodidad premium con materiales que absorben el sudor.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 309,
    nombre: 'Pantaloneta Decathlon Kipsta Pro',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrvDrarlh7o1_AwES7KPoaA0Eaz7mKL4TFoA&s',
    precio: 28,
    tallas: ['S', 'M', 'L'],
    colores: ['Azul', 'Naranja', 'Blanco'],
    descripcion: 'Pantaloneta asequible para entrenamientos recreativos.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 310,
    nombre: 'Pantaloneta Nike Dri-FIT Icon',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeCc6T3Lld4NGqgg4sQUSK7mivxTnr6z56ow&s',
    precio: 45,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Rojo', 'Blanco'],
    descripcion: 'Tecnología avanzada que combina estilo y funcionalidad.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 311,
    nombre: 'Pantaloneta Adidas Basketball Essentials',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0ewZhjK6nIuTm3rqQaV3hrj5Ab2w8pzbgdQ&s',
    precio: 39,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Azul', 'Gris', 'Negro'],
    descripcion: 'Perfecta para entrenamientos y partidos recreativos.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 312,
    nombre: 'Pantaloneta Jordan Flight',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJbUJZ9drsh472g5D3XEEZ-Q8z61IZBCy9Gw&s',
    precio: 52,
    tallas: ['M', 'L', 'XL'],
    colores: ['Blanco', 'Negro', 'Azul'],
    descripcion: 'Diseño premium con ajuste óptimo para cada movimiento.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 313,
    nombre: 'Pantaloneta Under Armour Sportstyle',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmg7-MUVsLCdFa6ppfzGu_N_SK2DRUcOT1KA&s',
    precio: 43,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Verde', 'Naranja'],
    descripcion: 'Comodidad y transpirabilidad para un juego competitivo.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 314,
    nombre: 'Pantaloneta Puma Court Flex',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLUqbuZ3MgX7zNWStz3m_oZXliHYkUN35Xrg&s',
    precio: 40,
    tallas: ['S', 'M', 'L'],
    colores: ['Negro', 'Rojo', 'Gris'],
    descripcion: 'Ligera y cómoda, ideal para partidos y entrenamiento.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 315,
    nombre: 'Pantaloneta Spalding Speed',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXzpZW1syqGhYWmO9V1D62kH5t9itC7mSwbA&s',
    precio: 33,
    tallas: ['M', 'L', 'XL'],
    colores: ['Rojo', 'Negro', 'Blanco'],
    descripcion: 'Diseño que favorece el rendimiento y la velocidad en la cancha.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 316,
    nombre: 'Pantaloneta Nike Dry Elite',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsIdVBBvHmltSzWo60noU-qbbLP3OfczVgZA&s',
    precio: 44,
    tallas: ['S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Azul', 'Blanco'],
    descripcion: 'Tecnología Dri-FIT para un ajuste seco y cómodo.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 317,
    nombre: 'Pantaloneta Reebok Flex',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdoX7IsxGmjA0wZz64lz7k4r4Zog_vHc8dXw&s',
    precio: 36,
    tallas: ['M', 'L', 'XL'],
    colores: ['Blanco', 'Negro', 'Gris'],
    descripcion: 'Ajuste cómodo con materiales ligeros y transpirables.',
    categoria: 'Pantalonetas',
    section: 'basquet'
  },
  {
    id: 101,
    nombre: 'Nike Air Zoom BB NXT',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://images.stockx.com/images/Nike-Air-Zoom-BB-NXT-Rawthentic-Product.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1686755772',
    precio: 150,
    tallas: ['8', '9', '10', '11', '12'],
    colores: ['Negro', 'Blanco', 'Azul'],
    descripcion: 'zapatos ligeros y con excelente amortiguación para un mejor rendimiento en la cancha.',
  },
  {
    id: 102,
    nombre: 'Adidas Harden Vol. 5',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU5Cx49WOQTURtCXwTe9EzrboDPcdNjMdYXQ&s',
    precio: 140,
    tallas: ['7', '8', '9', '10', '11'],
    colores: ['Rojo', 'Negro', 'Blanco'],
    descripcion: 'Diseñados para la velocidad y el control, ideales para jugadores dinámicos.',
  },
  {
    id: 103,
    nombre: 'Under Armour Curry Flow 9',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://m.media-amazon.com/images/I/61hqOc4mF3L._AC_UY900_.jpg',
    precio: 160,
    tallas: ['8', '9', '10', '11', '12'],
    colores: ['Amarillo', 'Negro', 'Blanco'],
    descripcion: 'Desarrollados para una tracción impecable y comodidad superior.',
  },
  {
    id: 104,
    nombre: 'Puma Clyde All-Pro',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNQ-0Buh8cStDorM-J9lC8JC0ecoGI1j8iRA&s',
    precio: 130,
    tallas: ['7', '8', '9', '10', '11'],
    colores: ['Gris', 'Negro', 'Rojo'],
    descripcion: 'Un clásico renovado con tecnología moderna para un gran desempeño.',
  },
  {
    id: 105,
    nombre: 'Reebok Question Mid',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu2CAfZOeKAbWF6R6R74gt_l9jSTlYLeAljQ&s',
    precio: 120,
    tallas: ['8', '9', '10', '11', '12'],
    colores: ['Blanco', 'Rojo', 'Azul'],
    descripcion: 'Inspirados en los clásicos de los años 90, con estilo y comodidad.',
  },
  {
    id: 106,
    nombre: 'Jordan Why Not Zer0.4',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIp6QvNdrfrO81fQLiCpOjsMIsiHCGCCOjRA&s',
    precio: 150,
    tallas: ['9', '10', '11', '12', '13'],
    colores: ['Negro', 'Naranja', 'Blanco'],
    descripcion: 'zapatos de alto rendimiento diseñados para jugadores explosivos.',
  },   
  {
    id: 107,
    nombre: 'Converse All Star BB Jet',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFkGNdFfxwt4F4sXN0FufjyqcC99gWJNAfuw&s',
    precio: 110,
    tallas: ['7', '8', '9', '10', '11'],
    colores: ['Blanco', 'Negro', 'Verde'],
    descripcion: 'Estilo clásico combinado con tecnología moderna para la cancha.',
  },
  {
    id: 108,
    nombre: 'Li-Ning Way of Wade 10',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0-vZ-w4v4_2Q2ncAeNDn65PAlQeQPUrsUjQ&s',
    precio: 200,
    tallas: ['8', '9', '10', '11', '12'],
    colores: ['Negro', 'Morado', 'Rojo'],
    descripcion: 'Edición de lujo para un máximo rendimiento y estilo.',
  },
  {
    id: 109,
    nombre: 'Anta KT6',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://sheshalifestyle.com/wp-content/uploads/2023/05/1-122.png',
    precio: 140,
    tallas: ['8', '9', '10', '11', '12'],
    colores: ['Blanco', 'Azul', 'Negro'],
    descripcion: 'zapatos diseñados para soportar el ritmo intenso del baloncesto profesional.',
  },
  {
    id: 110,
    nombre: 'New Balance Kawhi',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0cUK8M4meC71kvktPXShhiAWr_BLRpVMElA&s',
    precio: 150,
    tallas: ['9', '10', '11', '12', '13'],
    colores: ['Rojo', 'Negro', 'Gris'],
    descripcion: 'Estilo y funcionalidad combinados para un gran control en la cancha.',
  },
  {
    id: 111,
    nombre: 'Nike KD14',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRivkwkbnGWUrgK8vF1q4Rt98NHJIfLXS9AlQ&s',
    precio: 160,
    tallas: ['8', '9', '10', '11', '12'],
    colores: ['Negro', 'Blanco', 'Morado'],
    descripcion: 'Diseñados para brindar una amortiguación excelente y estabilidad.',
  },

  {
    id: 112,
    nombre: 'Adidas Dame 7',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUMc-PiG6W66nAtoCjTqA6WGfdAplbhY-4FQ&s',
    precio: 130,
    tallas: ['7', '8', '9', '10', '11'],
    colores: ['Azul', 'Negro', 'Blanco'],
    descripcion: 'zapatos versátiles para un rendimiento excepcional en la cancha.',
  },
  {
    id: 113,
    nombre: 'Under Armour HOVR Havoc 3',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThxGf4Ic06bGujR7dEiFFQJqbCPesgjle4rw&s',
    precio: 140,
    tallas: ['9', '10', '11', '12', '13'],
    colores: ['Gris', 'Negro', 'Azul'],
    descripcion: 'Perfectos para jugadores que buscan comodidad y soporte duradero.',
  },
  {
    id: 114,
    nombre: 'Puma RS-Dreamer',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9H9QQeaObEi7I_kPVC77lF9kRZ4gQ-AolNg&s',
    precio: 125,
    tallas: ['8', '9', '10', '11', '12'],
    colores: ['Negro', 'Rojo', 'Blanco'],
    descripcion: 'zapatos dinámicos y estilizados para destacar dentro y fuera de la cancha.',
  },
  {
    id: 115,
    nombre: 'Reebok Kamikaze II',
    categoria: 'zapatos',
    section: 'basquet',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3jZl8YtGDm2naWuzm86sZUp5r74H5CHW4AA&s',
    precio: 110,
    tallas: ['8', '9', '10', '11', '12'],
    colores: ['Verde', 'Negro', 'Blanco'],
    descripcion: 'Un diseño clásico con un toque moderno para los amantes del baloncesto.',
  },
    {
      id: 1300,
      nombre: 'Camisa Brasil',
      imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYl970FxNToce-477Ei0xoXESxX1Tshd-XZQ&s',
      precio: 60,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Amarillo', 'Verde'],
      descripcion: 'Camisa oficial de la selección de Brasil, edición 2023.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1301,
      nombre: 'Camisa Argentina',
      imagen: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/85350dca156641ed95d7ae4b0133e9d4_9366/Camiseta_Local_Argentina_22_Blanco_HF1488_01_laydown.jpg',
      precio: 65,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Celeste', 'Blanco'],
      descripcion: 'Camiseta visitante de la selección Argentina, tecnología AEROREADY.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1302,
      nombre: 'Camisa Francia',
      imagen: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53d26e7b-e1fd-44f6-aa64-b46cfa40a93c/NK+24%2F25+W+Rep+Jersey+Player.png',
      precio: 70,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Azul', 'Rojo', 'Blanco'],
      descripcion: 'Camisa oficial de la selección francesa, diseño clásico.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1303,
      nombre: 'Camisa Alemania',
      imagen: 'https://prochampions.vtexassets.com/arquivos/ids/872342/Adidas-Dfb-H-Jsy-Camiseta-De-Equipo_IP8139_03.jpg?v=638491303871970000',
      precio: 68,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Negro', 'Rojo', 'Dorado'],
      descripcion: 'Camiseta alternativa de Alemania, diseño moderno.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1304,
      nombre: 'Camisa Inglaterra',
      imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4SO-cm5GSFFZf5mhIJoGMMu6hjTEh66ipSQ&s',
      precio: 65,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Blanco', 'Rojo', 'Azul'],
      descripcion: 'Camiseta oficial de Inglaterra, edición 2023.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1305,
      nombre: 'Camisa España',
      imagen: 'https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/eb28d02c163841b0b5de4d2fbbd7c296_9366/camiseta-local-espana-24-ninos.jpg',
      precio: 67,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Rojo', 'Amarillo'],
      descripcion: 'Camisa oficial de la selección española, diseño elegante.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1306,
      nombre: 'Camisa Italia',
      imagen: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c9a83acfaea84a31a559af2a00a6c867_9366/Camiseta_Local_Italia_23_Azul_HS9881_01_laydown.jpg',
      precio: 66,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Blanco', 'Verde'],
      descripcion: 'Camiseta alternativa de Italia, diseño clásico renovado.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1307,
      nombre: 'Camisa México',
      imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIf08bWm6LQZB7L3y7wte5Vt2tEjF9Lh50yQ&s',
      precio: 62,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Verde', 'Rojo', 'Blanco'],
      descripcion: 'Camiseta oficial de México, diseño tradicional.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1308,
      nombre: 'Camisa Japón',
      imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5wWytzu17OiyTNBbdVhTLWr2laCGUwhRBGQ&s',
      precio: 69,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Blanco', 'Azul'],
      descripcion: 'Camiseta alternativa de Japón, tecnología avanzada.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1309,
      nombre: 'Camisa Portugal',
      imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ8N5AqI-ZVFvK6sGNfYeTiQ8AJSJ6UdfGvA&s',
      precio: 65,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Rojo', 'Verde'],
      descripcion: 'Camiseta oficial de la selección de Portugal.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1310,
      nombre: 'Camisa Bélgica',
      imagen: 'https://assets.adidas.com/images/w_600,f_auto,q_auto/87dee0babbf840ba8de2ae99012e29e7_9366/Camiseta_Uniforme_de_Local_Belgica_22_Rojo_HD9412_01_laydown.jpg',
      precio: 68,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Blanco', 'Negro', 'Rojo'],
      descripcion: 'Camiseta alternativa de Bélgica, diseño dinámico.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1311,
      nombre: 'Camisa Uruguay',
      imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtwPn--Lcuz-LqiZSr9sY_8Ce0tiXr4u2hww&s',
      precio: 63,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Celeste', 'Negro'],
      descripcion: 'Camiseta oficial de Uruguay, edición 2023.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1312,
      nombre: 'Camisa Colombia',
      imagen: 'https://assets.adidas.com/images/w_600,f_auto,q_auto/f5beb132085840d28075ae77001384a1_9366/Camiseta_Local_Seleccion_Colombia_Amarillo_HD8847_01_laydown.jpg',
      precio: 64,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Azul', 'Amarillo'],
      descripcion: 'Camiseta alternativa de Colombia, tecnología Dri-FIT.',
      categoria: 'camisas',
      section: 'futbol'
    },
    {
      id: 1313,
      nombre: 'Camisa Chile',
      imagen: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/12d3c026cd0e4837ae4aaed6014883c4_9366/Camiseta_Local_Chile_22-23_Rojo_IC5176_01_laydown.jpg',
      precio: 62,
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Rojo', 'Azul', 'Blanco'],
      descripcion: 'Camiseta oficial de Chile, diseño impactante.',
      categoria: 'camisas',
      section: 'futbol'
    },
      {
        id: 1200,
        nombre: 'Pantaloneta Brasil',
        imagen: 'https://static.wixstatic.com/media/f20469_0cf41cb39e054c2ab6cf9691bb17306f~mv2.jpg/v1/fill/w_480,h_456,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/f20469_0cf41cb39e054c2ab6cf9691bb17306f~mv2.jpg',
        precio: 25,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Amarillo', 'Verde'],
        descripcion: 'Pantaloneta oficial de Brasil, perfecta para entrenamiento y partidos.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1201,
        nombre: 'Pantaloneta Argentina',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQh_1UMBpkZbrg7sFnMSyud4KoA0AzxNoL3wA&s',
        precio: 28,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Celeste', 'Blanco'],
        descripcion: 'Pantaloneta de Argentina, cómoda y ligera para jugar.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1202,
        nombre: 'Pantaloneta Francia',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqu6R1AR5Bdw55EVKWT2zmrKYOijUtCcEITA&s',
        precio: 30,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Azul', 'Rojo'],
        descripcion: 'Pantaloneta oficial de la selección francesa, tecnología de transpiración.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1203,
        nombre: 'Pantaloneta Alemania',
        imagen: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2eb263df6fa84d58bc03ae96009aae6d_9366/Shorts_Uniforme_de_Local_Alemania_22_Negro_HF1465_01_laydown.jpg',
        precio: 27,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Negro', 'Blanco'],
        descripcion: 'Pantaloneta de Alemania, diseño clásico y resistente.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1204,
        nombre: 'Pantaloneta Inglaterra',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY6jPWkkT7owK7US6jW-YsDkDNvdKfyzpBaw&s',
        precio: 29,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Blanco', 'Rojo'],
        descripcion: 'Pantaloneta oficial de Inglaterra, ligera y ergonómica.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1205,
        nombre: 'Pantaloneta España',
        imagen: 'https://www.futbolemotion.com/imagesarticulos/220189/grandes/pantalon-corto-adidas-espana-primera-equipacion-eurocopa-2024-victory-blue-4.webp',
        precio: 28,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Rojo', 'Amarillo'],
        descripcion: 'Pantaloneta de España, ideal para entrenamiento o juego.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1206,
        nombre: 'Pantaloneta Italia',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ02ThnjaremLYq_QdTxV0NeP5-e49sqpgQRQ&s',
        precio: 26,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Azul', 'Blanco'],
        descripcion: 'Pantaloneta oficial de Italia, diseño clásico y moderno.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1207,
        nombre: 'Pantaloneta México',
        imagen: 'https://assets.adidas.com/images/w_600,f_auto,q_auto/4dcc833fb5ec45fd9f19aee7000c0fb9_9366/Shorts_Local_Authentic_Seleccion_Nacional_de_Mexico_Verde_HU0315_01_laydown.jpg',
        precio: 25,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Verde', 'Rojo', 'Blanco'],
        descripcion: 'Pantaloneta de México, perfecta para todas las condiciones de juego.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1208,
        nombre: 'Pantaloneta Japón',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNVkslTCH-kCD9vNLMIknH_ipHBCoEunt3MA&s',
        precio: 27,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Blanco', 'Azul'],
        descripcion: 'Pantaloneta oficial de Japón, tecnología avanzada para mayor comodidad.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1209,
        nombre: 'Pantaloneta Portugal',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZQjwcdoEJvG9XbE4OJ_KvU7W363sqLzhdlQ&s',
        precio: 26,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Rojo', 'Verde'],
        descripcion: 'Pantaloneta de Portugal, ideal para entrenamiento o competencia.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1210,
        nombre: 'Pantaloneta Bélgica',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnGNw_aLV4rgvbfXSV_Vhmh4ohJkDXYbIM7A&s',
        precio: 28,
        tallas: ['S', 'M', 'L', 'XL'],
        colores: ['Negro', 'Rojo', 'Amarillo'],
        descripcion: 'Pantaloneta oficial de Bélgica, diseño moderno y cómodo.',
        categoria: 'pantaloneta',
        section: 'futbol'
      },
      {
        id: 1100,
        nombre: 'Nike Mercurial',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD6aRnCmjj6ery2b8e_ZiNB31J6qxOHtBHfw&s',
        precio: 120,
        tallas: ['38', '39', '40', '41', '42', '43', '44'],
        colores: ['Negro', 'Blanco', 'Rojo'],
        descripcion: 'Diseñados para máxima velocidad en el campo y un ajuste perfecto.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1101,
        nombre: 'Adidas Predator',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7JzU_Eo6leACsfJBPVTVAT_oT2v8O2UQlvQ&s',
        precio: 130,
        tallas: ['38', '39', '40', '41', '42', '43'],
        colores: ['Azul', 'Negro', 'Blanco'],
        descripcion: 'Control total del balón con tecnología avanzada.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1102,
        nombre: 'Puma Future Z',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKY9sKfDT_qn3mY9VSYLXCGbxBkNW_rhpicg&s',
        precio: 110,
        tallas: ['38', '39', '40', '41', '42', '44'],
        colores: ['Naranja', 'Negro'],
        descripcion: 'Comodidad y flexibilidad para movimientos dinámicos.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1103,
        nombre: 'Under Armour Magnetico',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4A4_5sHeg-XOJYaxwsEXtlM8THmTw6uOQhw&s',
        precio: 95,
        tallas: ['38', '39', '40', '41', '42', '43', '44'],
        colores: ['Gris', 'Negro'],
        descripcion: 'Ajuste perfecto y tracción optimizada en cualquier superficie.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1104,
        nombre: 'Mizuno Morelia Neo',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThCroLfc5lTYtnCPTewOmm2R2-rbyk12QEJQ&s',
        precio: 140,
        tallas: ['39', '40', '41', '42', '43'],
        colores: ['Blanco', 'Dorado'],
        descripcion: 'Diseño clásico con materiales modernos para mayor durabilidad.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1105,
        nombre: 'New Balance Tekela',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1fOWzo5NzfX4T_82qbMgc_cV60PR3TCHvVg&s',
        precio: 105,
        tallas: ['38', '39', '40', '41', '42', '43'],
        colores: ['Verde', 'Negro'],
        descripcion: 'Control preciso y soporte en movimientos rápidos.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1106,
        nombre: 'Umbro Velocita',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWiGdNv6TJ6iXU7nzyD6PMHiT0826J2hLSvg&s',
        precio: 100,
        tallas: ['39', '40', '41', '42', '43', '44'],
        colores: ['Amarillo', 'Azul'],
        descripcion: 'Ligereza y velocidad en el diseño.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1107,
        nombre: 'Diadora Brasil',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtI1U-uLd51AnlHUE-zGLhxKBTqdr_gMVxYw&s',
        precio: 90,
        tallas: ['38', '39', '40', '41', '42'],
        colores: ['Rojo', 'Blanco'],
        descripcion: 'Inspirados en el estilo clásico de los campos brasileños.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1108,
        nombre: 'Joma Champion',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO68YK80eEtolptfaiKO_zV0cBXPaeQA8rHQ&s',
        precio: 85,
        tallas: ['38', '39', '40', '41', '42', '43'],
        colores: ['Negro', 'Blanco'],
        descripcion: 'Alta resistencia y comodidad para largas jornadas de juego.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1109,
        nombre: 'Kelme Precision',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyo1M9b9C573rO5EMtfJ_Cop-zr-ul6vM53Q&s',
        precio: 75,
        tallas: ['39', '40', '41', '42', '43'],
        colores: ['Negro', 'Gris'],
        descripcion: 'Control preciso y diseño robusto para jugadores técnicos.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1110,
        nombre: 'Lotto Solista',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDNFTPlaDQJOYIs2Y_59b1u7y6PKsD1eiYww&s',
        precio: 92,
        tallas: ['38', '39', '40', '41', '42', '43', '44'],
        colores: ['Azul', 'Negro'],
        descripcion: 'Velocidad y agilidad en cada jugada.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1111,
        nombre: 'Reebok Classic Soccer',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZvPzJk54cgiXPAJ440XIBm9-ylY72sr_kSw&s',
        precio: 80,
        tallas: ['38', '39', '40', '41', '42', '43'],
        colores: ['Blanco', 'Negro'],
        descripcion: 'Diseño clásico para una experiencia moderna en el campo.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1112,
        nombre: 'Asics DS Light',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKbSzV5Pv00OGLaaFchCoiofwvsATlrf0Xfg&s',
        precio: 115,
        tallas: ['38', '39', '40', '41', '42', '43', '44'],
        colores: ['Rojo', 'Negro'],
        descripcion: 'Ligereza y soporte para largas sesiones de juego.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1113,
        nombre: 'Nike Phantom',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmeCZN5vdRJimteRRRfi9_U_kE-mn1-2ULvw&s',
        precio: 125,
        tallas: ['38', '39', '40', '41', '42', '43'],
        colores: ['Negro', 'Blanco', 'Amarillo'],
        descripcion: 'Para jugadores que buscan control absoluto en el campo.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1114,
        nombre: 'Adidas X Speedflow',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCaia5bSJR08snTnUlTU7BxP4oYhsdC1jFNQ&s',
        precio: 140,
        tallas: ['39', '40', '41', '42', '43'],
        colores: ['Negro', 'Rojo'],
        descripcion: 'Rapidez y agilidad para los jugadores más exigentes.',
        categoria: 'zapatos',
        section: 'futbol'
      },
      {
        id: 1115,
        nombre: 'Puma King',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6l0tRZUmTS4SgFwDlDDINqD1yKVs9mGG_Fw&s',
        precio: 105,
        tallas: ['39', '40', '41', '42', '43'],
        colores: ['Negro', 'Blanco'],
        descripcion: 'Diseño clásico y excelente confort en cada paso.',
        categoria: 'zapatos',
        section: 'futbol'
      }
          ];

